name: DAG Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm gate:left
      - run: pnpm test:unit
      - run: pnpm test:e2e
      - run: pnpm build
      - run: pnpm gate:right
      - run: node tools/audit_external.js

# 失敗時の扱い: gate/right/audit が失敗すると job は fail します。
# 方針: 失敗ブランチは z/past に差し戻すこと。
