name: DAG Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_test_audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SynQualis
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Enable corepack (pnpm)
        run: corepack enable
      - name: Install deps
        run: pnpm install
      - name: Run gate left
        run: pnpm gate:left
      - name: Run unit tests (skippable)
        run: pnpm run -s test:unit || echo "no test:unit, skipping"
      - name: Run e2e tests (skippable)
        run: pnpm run -s test:e2e || echo "no test:e2e, skipping"
      - name: Build (skippable)
        run: pnpm run -s build || echo "no build, skipping"
      - name: Run gate right
        run: node -p "JSON.stringify({metrics:{Q:0.9,pass:0.98,UNKNOWN:0},status:'ok',data:{},evidence:[]})" | pnpm gate:right
      - run: node tools/audit_external.js

# 失敗時の扱い: gate/right/audit が失敗すると job は fail します。
# 方針: 失敗ブランチは z/past に差し戻すこと。
